server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:  # 开启动态路由
        locator:
          enabled: true
      routes:
        # 这里是配置 将8001 的服务不主动暴露出来  通过网关来访问
        - id: payment_routh1
          uri: lb://CLOUD-PAYMENT-SERVICE # lb 是load balance的意思 8001 端口 和8002 端口的微服务都提供一样的服务
          predicates:
            - Path=/payment/getById/**
            #当前时间和下边这个时间做对比 如果晚于这个时间 则可以访问 反正拒绝
#            - After=2010-10-30T18:25:10.272410800+08:00[Asia/Shanghai]
#            - Before=2010-10-30T18:25:10.272410800+08:00[Asia/Shanghai]
#            - Between=2010-10-30T18:25:10.272410800+08:00[Asia/Shanghai]，2030-10-30T18:25:10.272410800+08:00[Asia/Shanghai]
            # 需要提交cookie中包含 username=xxxx   curl http://localhost:9527/payment/getById/1 --cookie "username=xxxx"
#            - Cookie=username,xxxx
            - Header=X-Request-Id,\d+ # 要求请求头中有 X-Request-Id 属性并且值为整数的正则表达式
        - id: payment_routh2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
