# 我win10ip地址为192.168.43.200 虚拟机linux ip为192.168.43.50
server:
  port: 80

spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      host: 192.168.43.50   #consul的ip地址  也就是虚拟机的ip
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        ip-address: 192.168.43.200  # 这里需要配置虚拟机docker的consul内部访问外部实体机的地址
        port: 80    #payment的端口号


